name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-noir:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.3
        with:
          toolchain: v0.19.4

      - name: Run nargo test
        run: |
          nargo test